# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cable_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 305)
        MainWindow.setStyleSheet("background-color: rgb(1,31,75);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 481, 305))
        self.stackedWidget.setMinimumSize(QtCore.QSize(481, 300))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1000, 500))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_cable = QtWidgets.QGroupBox(self.page_1)
        self.group_cable.setMinimumSize(QtCore.QSize(429, 67))
        self.group_cable.setMaximumSize(QtCore.QSize(500, 67))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.group_cable.setFont(font)
        self.group_cable.setStyleSheet("QGroupBox{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.group_cable.setObjectName("group_cable")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_cable)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cable_filename = QtWidgets.QLineEdit(self.group_cable)
        self.cable_filename.setMinimumSize(QtCore.QSize(0, 22))
        self.cable_filename.setMaximumSize(QtCore.QSize(328, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.cable_filename.setFont(font)
        self.cable_filename.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 1px\n"
"}")
        self.cable_filename.setText("")
        self.cable_filename.setObjectName("cable_filename")
        self.horizontalLayout_2.addWidget(self.cable_filename)
        self.cable_browsefile_button = QtWidgets.QPushButton(self.group_cable)
        self.cable_browsefile_button.setMinimumSize(QtCore.QSize(75, 23))
        self.cable_browsefile_button.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.cable_browsefile_button.setFont(font)
        self.cable_browsefile_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.cable_browsefile_button.setObjectName("cable_browsefile_button")
        self.horizontalLayout_2.addWidget(self.cable_browsefile_button)
        self.verticalLayout_2.addWidget(self.group_cable)
        self.group_board_a = QtWidgets.QGroupBox(self.page_1)
        self.group_board_a.setMinimumSize(QtCore.QSize(429, 131))
        self.group_board_a.setMaximumSize(QtCore.QSize(500, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.group_board_a.setFont(font)
        self.group_board_a.setStyleSheet("QGroupBox{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.group_board_a.setObjectName("group_board_a")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_board_a)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.group_board_a)
        self.frame.setMinimumSize(QtCore.QSize(410, 71))
        self.frame.setMaximumSize(QtCore.QSize(500, 137))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.board_a_filename = QtWidgets.QLineEdit(self.frame)
        self.board_a_filename.setMaximumSize(QtCore.QSize(328, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.board_a_filename.setFont(font)
        self.board_a_filename.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 1px\n"
"}")
        self.board_a_filename.setText("")
        self.board_a_filename.setObjectName("board_a_filename")
        self.gridLayout.addWidget(self.board_a_filename, 0, 0, 1, 1)
        self.board_a_confirm_button = QtWidgets.QPushButton(self.frame)
        self.board_a_confirm_button.setMinimumSize(QtCore.QSize(75, 23))
        self.board_a_confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.board_a_confirm_button.setFont(font)
        self.board_a_confirm_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.board_a_confirm_button.setObjectName("board_a_confirm_button")
        self.gridLayout.addWidget(self.board_a_confirm_button, 0, 1, 1, 1)
        self.board_b_filename = QtWidgets.QLineEdit(self.frame)
        self.board_b_filename.setMaximumSize(QtCore.QSize(328, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.board_b_filename.setFont(font)
        self.board_b_filename.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 1px\n"
"}")
        self.board_b_filename.setText("")
        self.board_b_filename.setObjectName("board_b_filename")
        self.gridLayout.addWidget(self.board_b_filename, 1, 0, 1, 1)
        self.board_b_confirm_button = QtWidgets.QPushButton(self.frame)
        self.board_b_confirm_button.setMinimumSize(QtCore.QSize(75, 23))
        self.board_b_confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.board_b_confirm_button.setFont(font)
        self.board_b_confirm_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.board_b_confirm_button.setObjectName("board_b_confirm_button")
        self.gridLayout.addWidget(self.board_b_confirm_button, 1, 1, 1, 1)
        self.board_c_filename = QtWidgets.QLineEdit(self.frame)
        self.board_c_filename.setMaximumSize(QtCore.QSize(328, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.board_c_filename.setFont(font)
        self.board_c_filename.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 1px\n"
"}")
        self.board_c_filename.setText("")
        self.board_c_filename.setObjectName("board_c_filename")
        self.gridLayout.addWidget(self.board_c_filename, 2, 0, 1, 1)
        self.board_c_confirm_button = QtWidgets.QPushButton(self.frame)
        self.board_c_confirm_button.setMinimumSize(QtCore.QSize(75, 23))
        self.board_c_confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.board_c_confirm_button.setFont(font)
        self.board_c_confirm_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.board_c_confirm_button.setObjectName("board_c_confirm_button")
        self.gridLayout.addWidget(self.board_c_confirm_button, 2, 1, 1, 1)
        self.board_d_filename = QtWidgets.QLineEdit(self.frame)
        self.board_d_filename.setMaximumSize(QtCore.QSize(328, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.board_d_filename.setFont(font)
        self.board_d_filename.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 1px\n"
"}")
        self.board_d_filename.setText("")
        self.board_d_filename.setObjectName("board_d_filename")
        self.gridLayout.addWidget(self.board_d_filename, 3, 0, 1, 1)
        self.board_d_confirm_button = QtWidgets.QPushButton(self.frame)
        self.board_d_confirm_button.setMinimumSize(QtCore.QSize(75, 23))
        self.board_d_confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.board_d_confirm_button.setFont(font)
        self.board_d_confirm_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.board_d_confirm_button.setObjectName("board_d_confirm_button")
        self.gridLayout.addWidget(self.board_d_confirm_button, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.group_board_a)
        self.frame_confirm = QtWidgets.QFrame(self.page_1)
        self.frame_confirm.setMaximumSize(QtCore.QSize(500, 67))
        self.frame_confirm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_confirm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_confirm.setObjectName("frame_confirm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_confirm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.next_button = QtWidgets.QPushButton(self.frame_confirm)
        self.next_button.setMinimumSize(QtCore.QSize(75, 23))
        self.next_button.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.next_button.setFont(font)
        self.next_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.verticalLayout_2.addWidget(self.frame_confirm)
        self.stackedWidget.addWidget(self.page_1)
        self.page_3_port = QtWidgets.QWidget()
        self.page_3_port.setObjectName("page_3_port")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3_port)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.p1_frame_3_port = QtWidgets.QFrame(self.page_3_port)
        self.p1_frame_3_port.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p1_frame_3_port.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p1_frame_3_port.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p1_frame_3_port.setObjectName("p1_frame_3_port")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.p1_frame_3_port)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.p1_frame_3_port)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.p1_board_comboBox_3_port = QtWidgets.QComboBox(self.p1_frame_3_port)
        self.p1_board_comboBox_3_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_board_comboBox_3_port.setFont(font)
        self.p1_board_comboBox_3_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p1_board_comboBox_3_port.setObjectName("p1_board_comboBox_3_port")
        self.horizontalLayout_9.addWidget(self.p1_board_comboBox_3_port)
        self.p1_lineEdit_3_port = QtWidgets.QLineEdit(self.p1_frame_3_port)
        self.p1_lineEdit_3_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_lineEdit_3_port.setFont(font)
        self.p1_lineEdit_3_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p1_lineEdit_3_port.setText("")
        self.p1_lineEdit_3_port.setObjectName("p1_lineEdit_3_port")
        self.horizontalLayout_9.addWidget(self.p1_lineEdit_3_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.p1_frame_3_port)
        self.p2_frame_3_port = QtWidgets.QFrame(self.page_3_port)
        self.p2_frame_3_port.setStyleSheet("QFrame{\n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p2_frame_3_port.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p2_frame_3_port.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p2_frame_3_port.setObjectName("p2_frame_3_port")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.p2_frame_3_port)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.p2_frame_3_port)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.p2_board_comboBox_3_port = QtWidgets.QComboBox(self.p2_frame_3_port)
        self.p2_board_comboBox_3_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_board_comboBox_3_port.setFont(font)
        self.p2_board_comboBox_3_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p2_board_comboBox_3_port.setObjectName("p2_board_comboBox_3_port")
        self.horizontalLayout_6.addWidget(self.p2_board_comboBox_3_port)
        self.p2_lineEdit_3_port = QtWidgets.QLineEdit(self.p2_frame_3_port)
        self.p2_lineEdit_3_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_lineEdit_3_port.setFont(font)
        self.p2_lineEdit_3_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p2_lineEdit_3_port.setObjectName("p2_lineEdit_3_port")
        self.horizontalLayout_6.addWidget(self.p2_lineEdit_3_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.p2_frame_3_port)
        self.p3_frame_3_port = QtWidgets.QFrame(self.page_3_port)
        self.p3_frame_3_port.setStyleSheet("QFrame{\n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p3_frame_3_port.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p3_frame_3_port.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p3_frame_3_port.setObjectName("p3_frame_3_port")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.p3_frame_3_port)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.p3_frame_3_port)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.p3_board_comboBox_3_port = QtWidgets.QComboBox(self.p3_frame_3_port)
        self.p3_board_comboBox_3_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p3_board_comboBox_3_port.setFont(font)
        self.p3_board_comboBox_3_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p3_board_comboBox_3_port.setObjectName("p3_board_comboBox_3_port")
        self.horizontalLayout_7.addWidget(self.p3_board_comboBox_3_port)
        self.p3_lineEdit_3_port = QtWidgets.QLineEdit(self.p3_frame_3_port)
        self.p3_lineEdit_3_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p3_lineEdit_3_port.setFont(font)
        self.p3_lineEdit_3_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p3_lineEdit_3_port.setObjectName("p3_lineEdit_3_port")
        self.horizontalLayout_7.addWidget(self.p3_lineEdit_3_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.p3_frame_3_port)
        self.frame_2 = QtWidgets.QFrame(self.page_3_port)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.previous_button_3_port = QtWidgets.QPushButton(self.frame_2)
        self.previous_button_3_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.previous_button_3_port.setFont(font)
        self.previous_button_3_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.previous_button_3_port.setObjectName("previous_button_3_port")
        self.horizontalLayout_8.addWidget(self.previous_button_3_port, 0, QtCore.Qt.AlignLeft)
        self.confirm_button_3_port = QtWidgets.QPushButton(self.frame_2)
        self.confirm_button_3_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button_3_port.setFont(font)
        self.confirm_button_3_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.confirm_button_3_port.setObjectName("confirm_button_3_port")
        self.horizontalLayout_8.addWidget(self.confirm_button_3_port, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_3_port)
        self.page_2_port = QtWidgets.QWidget()
        self.page_2_port.setObjectName("page_2_port")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2_port)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.page_2_port)
        self.frame_6.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.p1_board_comboBox_2_port = QtWidgets.QComboBox(self.frame_6)
        self.p1_board_comboBox_2_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_board_comboBox_2_port.setFont(font)
        self.p1_board_comboBox_2_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p1_board_comboBox_2_port.setObjectName("p1_board_comboBox_2_port")
        self.horizontalLayout_10.addWidget(self.p1_board_comboBox_2_port)
        self.p1_lineEdit_2_port = QtWidgets.QLineEdit(self.frame_6)
        self.p1_lineEdit_2_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_lineEdit_2_port.setFont(font)
        self.p1_lineEdit_2_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p1_lineEdit_2_port.setObjectName("p1_lineEdit_2_port")
        self.horizontalLayout_10.addWidget(self.p1_lineEdit_2_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.page_2_port)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.p2_board_comboBox_2_port = QtWidgets.QComboBox(self.frame_3)
        self.p2_board_comboBox_2_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_board_comboBox_2_port.setFont(font)
        self.p2_board_comboBox_2_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p2_board_comboBox_2_port.setObjectName("p2_board_comboBox_2_port")
        self.horizontalLayout_11.addWidget(self.p2_board_comboBox_2_port)
        self.p2_lineEdit_2_port = QtWidgets.QLineEdit(self.frame_3)
        self.p2_lineEdit_2_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_lineEdit_2_port.setFont(font)
        self.p2_lineEdit_2_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p2_lineEdit_2_port.setObjectName("p2_lineEdit_2_port")
        self.horizontalLayout_11.addWidget(self.p2_lineEdit_2_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.page_2_port)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.page_2_port)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.previous_button_2_port = QtWidgets.QPushButton(self.frame_7)
        self.previous_button_2_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.previous_button_2_port.setFont(font)
        self.previous_button_2_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.previous_button_2_port.setObjectName("previous_button_2_port")
        self.horizontalLayout_12.addWidget(self.previous_button_2_port, 0, QtCore.Qt.AlignLeft)
        self.confirm_button_2_port = QtWidgets.QPushButton(self.frame_7)
        self.confirm_button_2_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button_2_port.setFont(font)
        self.confirm_button_2_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.confirm_button_2_port.setObjectName("confirm_button_2_port")
        self.horizontalLayout_12.addWidget(self.confirm_button_2_port, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page_2_port)
        self.page_4_port = QtWidgets.QWidget()
        self.page_4_port.setObjectName("page_4_port")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4_port)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.p1_frame_3_port_4 = QtWidgets.QFrame(self.page_4_port)
        self.p1_frame_3_port_4.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p1_frame_3_port_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p1_frame_3_port_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p1_frame_3_port_4.setObjectName("p1_frame_3_port_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.p1_frame_3_port_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.p1_frame_3_port_4)
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.p1_board_comboBox_4_port = QtWidgets.QComboBox(self.p1_frame_3_port_4)
        self.p1_board_comboBox_4_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_board_comboBox_4_port.setFont(font)
        self.p1_board_comboBox_4_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p1_board_comboBox_4_port.setObjectName("p1_board_comboBox_4_port")
        self.horizontalLayout_14.addWidget(self.p1_board_comboBox_4_port)
        self.p1_lineEdit_4_port = QtWidgets.QLineEdit(self.p1_frame_3_port_4)
        self.p1_lineEdit_4_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p1_lineEdit_4_port.setFont(font)
        self.p1_lineEdit_4_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p1_lineEdit_4_port.setText("")
        self.p1_lineEdit_4_port.setObjectName("p1_lineEdit_4_port")
        self.horizontalLayout_14.addWidget(self.p1_lineEdit_4_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.p1_frame_3_port_4)
        self.p2_frame_port_4 = QtWidgets.QFrame(self.page_4_port)
        self.p2_frame_port_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p2_frame_port_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p2_frame_port_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p2_frame_port_4.setObjectName("p2_frame_port_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.p2_frame_port_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.p2_frame_port_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.p2_board_comboBox_4_port = QtWidgets.QComboBox(self.p2_frame_port_4)
        self.p2_board_comboBox_4_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_board_comboBox_4_port.setFont(font)
        self.p2_board_comboBox_4_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p2_board_comboBox_4_port.setObjectName("p2_board_comboBox_4_port")
        self.horizontalLayout_15.addWidget(self.p2_board_comboBox_4_port)
        self.p2_lineEdit_4_port = QtWidgets.QLineEdit(self.p2_frame_port_4)
        self.p2_lineEdit_4_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p2_lineEdit_4_port.setFont(font)
        self.p2_lineEdit_4_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p2_lineEdit_4_port.setObjectName("p2_lineEdit_4_port")
        self.horizontalLayout_15.addWidget(self.p2_lineEdit_4_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.p2_frame_port_4)
        self.p3_frame_port_4 = QtWidgets.QFrame(self.page_4_port)
        self.p3_frame_port_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p3_frame_port_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p3_frame_port_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p3_frame_port_4.setObjectName("p3_frame_port_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.p3_frame_port_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.p3_frame_port_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.p3_board_comboBox_4_port = QtWidgets.QComboBox(self.p3_frame_port_4)
        self.p3_board_comboBox_4_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p3_board_comboBox_4_port.setFont(font)
        self.p3_board_comboBox_4_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p3_board_comboBox_4_port.setObjectName("p3_board_comboBox_4_port")
        self.horizontalLayout_16.addWidget(self.p3_board_comboBox_4_port)
        self.p3_lineEdit_4_port = QtWidgets.QLineEdit(self.p3_frame_port_4)
        self.p3_lineEdit_4_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p3_lineEdit_4_port.setFont(font)
        self.p3_lineEdit_4_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p3_lineEdit_4_port.setObjectName("p3_lineEdit_4_port")
        self.horizontalLayout_16.addWidget(self.p3_lineEdit_4_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.p3_frame_port_4)
        self.p4_frame_port_4 = QtWidgets.QFrame(self.page_4_port)
        self.p4_frame_port_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(3,57,108);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.p4_frame_port_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p4_frame_port_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p4_frame_port_4.setObjectName("p4_frame_port_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.p4_frame_port_4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.p4_frame_port_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_17.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.p4_board_comboBox_4_port = QtWidgets.QComboBox(self.p4_frame_port_4)
        self.p4_board_comboBox_4_port.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p4_board_comboBox_4_port.setFont(font)
        self.p4_board_comboBox_4_port.setStyleSheet("QComboBox{\n"
"    background-color: rgb(179,205,224);\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"    border:2px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    \n"
"    \n"
"    color: #fff;\n"
"    font-size:12px;\n"
"    border:1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #b3cde0;\n"
"    outline: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.p4_board_comboBox_4_port.setObjectName("p4_board_comboBox_4_port")
        self.horizontalLayout_17.addWidget(self.p4_board_comboBox_4_port)
        self.p4_lineEdit_4_port = QtWidgets.QLineEdit(self.p4_frame_port_4)
        self.p4_lineEdit_4_port.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.p4_lineEdit_4_port.setFont(font)
        self.p4_lineEdit_4_port.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(179,205,224);\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid white;\n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}\n"
"")
        self.p4_lineEdit_4_port.setObjectName("p4_lineEdit_4_port")
        self.horizontalLayout_17.addWidget(self.p4_lineEdit_4_port, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.p4_frame_port_4)
        self.frame_4 = QtWidgets.QFrame(self.page_4_port)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.previous_button_4_port = QtWidgets.QPushButton(self.frame_4)
        self.previous_button_4_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.previous_button_4_port.setFont(font)
        self.previous_button_4_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.previous_button_4_port.setObjectName("previous_button_4_port")
        self.horizontalLayout_13.addWidget(self.previous_button_4_port, 0, QtCore.Qt.AlignLeft)
        self.confirm_button_4_port = QtWidgets.QPushButton(self.frame_4)
        self.confirm_button_4_port.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button_4_port.setFont(font)
        self.confirm_button_4_port.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0,91,150);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 123, 199);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 2px solid #b3cde0;\n"
"}\n"
"")
        self.confirm_button_4_port.setObjectName("confirm_button_4_port")
        self.horizontalLayout_13.addWidget(self.confirm_button_4_port, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_4_port)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_cable.setTitle(_translate("MainWindow", "Cable file"))
        self.cable_browsefile_button.setText(_translate("MainWindow", "Browse"))
        self.group_board_a.setTitle(_translate("MainWindow", "Involved Board Netlist"))
        self.board_a_confirm_button.setText(_translate("MainWindow", "Browse"))
        self.board_b_confirm_button.setText(_translate("MainWindow", "Browse"))
        self.board_c_confirm_button.setText(_translate("MainWindow", "Browse"))
        self.board_d_confirm_button.setText(_translate("MainWindow", "Browse"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "<strong>P1</strong>"))
        self.label_2.setText(_translate("MainWindow", "<strong>P2</strong>"))
        self.label_3.setText(_translate("MainWindow", "<strong>P3</strong>"))
        self.previous_button_3_port.setText(_translate("MainWindow", "Previous"))
        self.confirm_button_3_port.setText(_translate("MainWindow", "Confirm"))
        self.label_4.setText(_translate("MainWindow", "P1"))
        self.label_5.setText(_translate("MainWindow", "P2"))
        self.previous_button_2_port.setText(_translate("MainWindow", "Previous"))
        self.confirm_button_2_port.setText(_translate("MainWindow", "Confirm"))
        self.label_6.setText(_translate("MainWindow", "<strong>P1</strong>"))
        self.label_7.setText(_translate("MainWindow", "<strong>P2</strong>"))
        self.label_8.setText(_translate("MainWindow", "<strong>P3</strong>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">P4</span></p></body></html>"))
        self.previous_button_4_port.setText(_translate("MainWindow", "Previous"))
        self.confirm_button_4_port.setText(_translate("MainWindow", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
